package converter

import (
	"encoding/json"
	"github.com/eclipse/paho.mqtt.golang"
	"github.com/koestler/go-mqtt-to-influxdb/influxDbClient"
	"log"
	"regexp"
	"time"
)

type TelemetryMessage struct {
	Time     string
	NextTele string
	TimeZone string
	Model    string
	Values   map[string]struct {
		Value float64
		Unit  string
	}
}

var topicMatcher = regexp.MustCompile("^(.*)/([^/]*)$")

// parses messages generated by the go-ve-sensors tool in the format given by TelemetryMessage
// and write one point per value to the influxdb
func goVeSensorHandler(c Config, out Output, msg mqtt.Message) {
	// parse topic
	matches := topicMatcher.FindStringSubmatch(msg.Topic())
	if len(matches) < 3 {
		log.Printf("go-ve-sensor[%s]: cannot extract device from topic='%s", c.Name(), msg.Topic())
		return
	}
	device := matches[2]

	// parse payload
	var message TelemetryMessage
	if err := json.Unmarshal(msg.Payload(), &message); err != nil {
		log.Printf("go-ve-sensor[%s]: cannot json decode: %s", c.Name(), err)
		return
	}

	// map values to points
	points := make(influxDbClient.Points, len(message.Values))
	i := 0
	for field, value := range message.Values {
		points[i] = influxDbClient.Point{
			Tags: map[string]string{
				"device": device,
				"field":  field,
				"unit":   value.Unit,
				"sensor": message.Model,
			},
			Fields: map[string]interface{}{
				"value": value.Value,
			},
		}
		i += 1
	}

	if message.TimeZone != "UTC" {
		log.Printf("go-ve-sensor[%s]: TimeZone='%s' but only 'UTC' is supported", c.Name(), message.TimeZone)
	}

	timeStamp, err := parseTime(message.Time)
	if err != nil {
		timeStamp = time.Now()
	}

	out.WriteRawPoints(points.ToRaw(c.TargetMeasurement(), timeStamp), c.InfluxDbClients())
}
