version: "3"
services:
  go-mqtt-to-influx:
    restart: always
    image: koestler/go-mqtt-to-influx:v2
    volumes:
      - /srv/volumes/mqtt-to-influx/db:/app/db
      - ${PWD}/config.yaml:/app/config.yaml:ro