name: Run tests

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install tools
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0

      - name: Generate Mocks
        run: go generate -v ./...

      - name: Test
        run: go test -v ./...
