name: Audit & Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify dependencies
        run: go mod verify

      - name: Install tools
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0

      - name: Generate Mocks
        run: go generate -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Test
        run: go test -v ./...